---
- name: helm deployment 
  hosts: localhost
  gather_facts: False
   
  tasks:

    - name: copy deployment package to remote server
      copy:
        src: ./Demo-ACH_master/*.tgz
        dest: /home/ubuntu/tmp/
        mode: 0600

    # - name: Print debug message
      # debug:
        # msg: Hello, world!    

    # - name: copy deployment script
      # copy:
        # src: ./playbooks/main.sh
        # dest: /home/ubuntu/tmp/
        # mode: 0600

    # - name: create deployment list
      # script: ./ubuntu/tmp/main.sh

  #delegate_to: localhost