---
- name: helm deployment 
  hosts: servers
  gather_facts: False
   
  tasks:

    - name: copy deployment package to remote server
      copy:
        src: /var/lib/jenkins/workspace/Demo-ACH_master/demochat-0.1.0.tgz
        dest: /home/ubuntu/tmp/
        mode: 0644

    - name: copy deployment package to remote server
      copy:
        src: /home/ubuntu/environment/kamal/ansible-demo/testing/playbooks/main.s
        dest: /home/ubuntu/tmp/
        mode: 0644    

    - name: deploy helm chart
      script: main.sh

