---
- name: helm deployment 
  hosts: servers
  gather_facts: False
   
  tasks:

    - name: copy deployment package to remote server
      copy:
        src: ./playbooks
        dest: /home/ubuntu/tmp/
        mode: 0644
    
    - name: copy deployment script
      copy:
        src: ./playbooks/main.sh
        dest: /home/ubuntu/tmp/
        mode: 0644

    - name: create deployment list
      script: ./ubuntu/tmp/main.sh

  #delegate_to: localhost
